import { Action } from "../../types/action.types";

export const GENERATOR_GIT: Action[] = [
  {
    id: "git-status",
    name: "Git Status",
    description: "Affiche les fichiers modifiés, supprimés et non suivis",
    category: "git",
    script: "git/git-status.js",
    allowMultiple: true,
  },
  {
    id: "git-branch-tree-local",
    name: "Branches (local)",
    description: "Affiche l’arborescence des branches et commits locaux",
    category: "git",
    script: "git/git-branch-tree-local.js",
    allowMultiple: false,
  },
  {
    id: "git-branch-tree-remote",
    name: "Branches (remote)",
    description: "Récupère et synchronise les branches distantes",
    category: "git",
    script: "git/git-branch-tree-remote.js",
    allowMultiple: false,
  },
  {
    id: "git-delete-branch",
    name: "Supprimer une branche",
    description: "Supprime une branche locale ou distante",
    category: "git",
    script: "git/git-delete-branch.js",
    allowMultiple: false,
  },
  {
    id: "git-create-branch",
    name: "Créer une branche",
    description: "Crée une nouvelle branche à partir de la branche courante",
    category: "git",
    script: "git/git-create-branch.js",
    allowMultiple: false,
  },
  {
    id: "git-commit",
    name: "Créer un commit",
    description: "Ajoute les fichiers au staging et crée un commit",
    category: "git",
    script: "git/git-commit.js",
    allowMultiple: false,
  },
  {
    id: "git-squash-branch",
    name: "Squash en un commit",
    description: "Regroupe tous les commits de la branche en un seul commit",
    category: "git",
    script: "git/git-squash-branch.js",
    allowMultiple: false,
  },
];